AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  decifuck

Globals:
  Function:
    Timeout: 60

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: deciplus-credentials

  Decifuck:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./decifuck
      Handler: decifuck.handler
      Runtime: python3.8
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref Secret
        - SSMParameterReadPolicy:
            ParameterName: !Ref WantedSlots
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Input: |
              {
                "secret_name": "deciplus-credentials",
                "wanted_slots_parameter_name": "decifuck-wanted-slots"
              }

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      MetricName: Errors
      Threshold: 1
      Namespace: AWS/Lambda
      Statistic: Maximum
      TreatMissingData: notBreaching
      OKActions:
        - !Ref SNSTopic
      AlarmActions:
        - !Ref SNSTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref Decifuck

  WantedSlots:
    Type: AWS::SSM::Parameter
    Properties:
      Name: decifuck-wanted-slots
      Type: String
      Value: '{}'

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: mathieu.brochard@outlook.com
        - Protocol: email
          Endpoint: maelle.leherisse@gmail.com