AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  decifuck

Globals:
  Function:
    Timeout: 60

Resources:
  Decifuck:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./decifuck
      Handler: decifuck.handler
      Runtime: python3.8
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Enabled: False
            Schedule: rate(30 minutes)