name: Deploy Serverless

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install
      
    - name: Run tests
      run: npm t

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
